-- P2.4 Topic Hub weekly digest cache.
-- Rows are generated by digest.service per ISO-week starting Mon 00:00
-- Asia/Seoul. Empty weeks (no revisions / new refs / events / popular
-- posts) intentionally do NOT get a row.

-- CreateTable
CREATE TABLE "topic_hub_digests" (
    "id" UUID NOT NULL,
    "topic_hub_id" UUID NOT NULL,
    "period_start" TIMESTAMPTZ(6) NOT NULL,
    "period_end" TIMESTAMPTZ(6) NOT NULL,
    "payload" JSONB NOT NULL,
    "generated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "topic_hub_digests_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "topic_hub_digests_topic_hub_id_period_start_key"
    ON "topic_hub_digests"("topic_hub_id", "period_start");

-- CreateIndex
CREATE INDEX "topic_hub_digests_topic_hub_id_period_end_idx"
    ON "topic_hub_digests"("topic_hub_id", "period_end" DESC);

-- AddForeignKey
ALTER TABLE "topic_hub_digests"
    ADD CONSTRAINT "topic_hub_digests_topic_hub_id_fkey"
    FOREIGN KEY ("topic_hub_id") REFERENCES "topic_hubs"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;
